services:
  gcore-ddns:
    image: ghcr.io/begosh/ddns-gcore:main
    container_name: gcore-ddns
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - GCORE_CONFIG_PATH=/app/config.yaml
